### ISSUE TITLE
Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by cyrilepinat** [gruntjs/grunt-contrib-imagemin#325]
Hi, I cannot figure out what is happening here, and how to fix it. When I run `grunt imagemin -vd --stack`

I get that : 

        Options: interlaced, optimizationLevel=3, progressive, cache=false
	Fatal error: Cannot read property 'contents' of undefined
	TypeError: Cannot read property 'contents' of undefined
	    at /home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:61:54
	    at ConcatStream.<anonymous> (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/index.js:36:43)
	    at ConcatStream.emit (events.js:129:20)
	    at finishMaybe (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:502:14)
	    at endWritable (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:512:3)
	    at ConcatStream.Writable.end (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:477:5)
	    at DuplexWrapper.onend (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:539:10)
	    at DuplexWrapper.g (events.js:199:16)
	    at DuplexWrapper.emit (events.js:129:20)
	    at endReadableNT (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:944:12)
	    at afterTick (/home/cyril/dev/workspace/client/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/node_modules/process-nextick-args/index.js:11:8)
	    at process._tickCallback (node.js:355:11)
 

Could you help me please ?
 
my config is : 

     grunt-contrib-imagemin : 0.9.4
     imagemin : 3.2.0

and in Gruntfile.js : 

     imagemin: {
	  dist: {
	    options: {
	      cache:false
	    },
	    files: [{
	      expand: true,
	      cwd: '<%= yeoman.app %>/assets',
	      src: ['**/*.{png,jpg,jpeg,gif}'],
	      dest: '<%= yeoman.dist %>/assets'
	    }]
	  }
	},

**Comment by adrhc** [comment]
I have the same problem with the environment:
Linux adr-desktop 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
npm 2.11.3
node v0.12.7

In addition at install I have errors e.g.:
  ⚠ Invalid non-string/buffer chunk
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:93:10)
    at DestroyableTransform.<anonymous> (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:50:10)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)
    at DestroyableTransform.Readable.push (/home/adr/Projects/photos/trunk/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
grunt-contrib-imagemin@0.9.4 node_modules/grunt-contrib-imagemin

**Comment by oaosman84** [comment]
Same problem - just started happening on the same exact sourcetree that was working before.

I think some underlying lib must have updated but can't figure out what.

**Comment by adrhc** [comment]
Oh, I forgot to mention:
when I'm removing grunt-contrib-imagemin and simply coping the previous used one (I change my system so I have a backup) everything works fine. 
The diff above is between these 2 versions of grunt-contrib-imagemin. Oh, as a matter of fact they are the same version too so I guess the problem is with the result of installation process for grunt-contrib-imagemin.

**Comment by clint42** [comment]
Same issue here. I've found a temporary workaround, by replacing imagemin version in grunt-contrib-imagemin package.json ("3.1.0" instead of "^3.1.0). But it's only temporary because package.json live inside node_modules/grunt-contrib-imagemin and my dirty fix will be overrided in case of update but more important it will not be present on my project git (so I'm unable to deploy). If you have a more clean way to force grunt-contrib-imagemin to use version 3.1.0 of imagemin it could be nice.

**Comment by damiendube** [comment]
Also started to have this issue yesterday. No code change...

**Comment by shinnn** [comment]
Duplicate of https://github.com/imagemin/imagemin/issues/129

**Comment by kfateem** [comment]
Resolved in imagemin@3.2.1

**Comment by asmerkin** [comment]
Hey guys, the library stream-combiner2 was updated last friday, spoiling everything. I hope imagemin 3.2.1 fixes this fine.

**Comment by bnlong** [comment]
This problem has just been fixed in the imagemin 3.2.2. I ran the following command to update imagemin and the problem disappeared.

npm install --save imagemin@3.2.2

**Comment by nitinsangal** [comment]
Hi, I am facing an issue "Fatal error: Cannot read property 'contents' of undefined" . if one .png is present then it raise error but  in case of all jpg image it works fine when i run command grunt build.

node version v0.10.38
npm version 3.3.5
grunt-contrib-imagemin 0.7.2
imagemin 3.2.1

and i was checked with imagemin@3.2.2 but not

**Comment by psergei** [comment]
Issues still happens. Using all latest imageimin 4.0.0, grunt-contrin-imagemin 0.9.4
Seems like one of the "stream" packages was updated.

**Comment by oaosman84** [comment]
Yes, we are also seeing it again.

**Comment by psergei** [comment]
It is easy to workaround in grunt contrib imagemin, but I would prefer a root cause fix.

**Comment by oaosman84** [comment]
How have you worked around it? I'm on grunt-contrib 0.9.4 which is pulling in imagemin 3.2.2

**Comment by psergei** [comment]
I just submitted pull request. It works for me.

**Comment by mingjunyang** [comment]
+1.
waitting resolve it.

```text
Linux mycompute 4.1.12-1-default #1 SMP PREEMPT Thu Oct 29 06:43:42 UTC 2015 (e24bad1) x86_64 x86_64 x86_64 GNU/Linux

node -v
v4.2.1

npm -v
2.14.7

npm list | grep image
├─┬ grunt-contrib-imagemin@0.9.4
│ ├─┬ imagemin@3.2.2
│ │ ├─┬ imagemin-gifsicle@4.2.0
│ │ ├─┬ imagemin-jpegtran@4.3.1
│ │ ├─┬ imagemin-optipng@4.3.0
│ │ ├─┬ imagemin-svgo@4.1.2

```

```sh 
 Fatal error: Cannot read property 'contents' of undefined
    
    
    Execution Time (2015-11-09 09:11:07 UTC)
    loading tasks                     6ms  ▇ 2%
    loading grunt-contrib-imagemin  182ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 63%
    imagemin:dist                   102ms  ▇▇▇▇▇▇▇▇▇▇▇ 35%
    Total 291ms Use --force to continue.
        
        Aborted due to warnings.
```

**Comment by chrisse27** [comment]
+1 for merging @psergei PR.

**Comment by ra-krishna** [comment]
+1 for merging @psergei PR.

**Comment by ra-krishna** [comment]
+1 for PR merge.

**Comment by wardoost** [comment]
+1 for merging @psergei fix

**Comment by mickro** [comment]
+1 for merging @psergei fix

**Comment by samgooch** [comment]
+1 for merging @psergei fix

**Comment by errok** [comment]
+1 for merging @psergei fix

**Comment by flim** [comment]
+1 for merging @psergei fix

**Comment by ganshee** [comment]
+1 for merging @psergei fix

**Comment by johannesjo** [comment]
+1 for merging @psergei fix asap!

**Comment by avidaniel** [comment]
+1 for merging @psergei

**Comment by jonixj** [comment]
+1 for merging @psergei

**Comment by lleitner** [comment]
+1 for merging @psergei fix

**Comment by Vitre** [comment]
+1 for merging @psergei fix

**Comment by NomadeLampe** [comment]
+1 for merging @psergei fix

**Comment by mjrk** [comment]
+1

**Comment by asmerkin** [comment]
+1

**Comment by enodata** [comment]
+1

**Comment by mywebdrag** [comment]
hey guys whats the latest version for the Fix. I have these installed
├─┬ grunt-contrib-imagemin@0.9.4
│ ├─┬ imagemin@3.2.2
│ │ ├─┬ imagemin-svgo@4.1.2

and its breaking as well.

**Comment by 0xadada** [comment]
Indeed, #329 did not fix.

**Comment by michaelsanford** [comment]
Note that the fix was pushed to npm as grunt-contrib-imagemin *1.0.0*.

If you have any lingering `"grunt-contrib-imagemin": "^0.9.2",` in your `package.json` you will need to update it to `"grunt-contrib-imagemin": "^1.0.0"` in order to get the update.

Confirmed fixed my end; thanks @vladikoff ! :clap:

/cc @mywebdrag @0xadada

**Comment by 0xadada** [comment]
Confirmed, fixed my problem too :facepunch: thanks @vladikoff  :kiss:

**Comment by Edgar160** [comment]
Worked for me too :clap:

**Comment by mywebdrag** [comment]
Confirmed, fixed my problem! Thanks!

**Comment by aroget** [comment]
@michaelsanford fixed it

**Comment by synarque** [comment]
Confirmed fix thanks !
